#!/usr/bin/env python3
"""Single source of truth for the site header.

The pages are self-contained on purpose (they get etched on-chain, and a reader
must work from a USB stick), so there is no runtime include to share. What we can
do is generate the shared block and let CI prove no copy has drifted:

    python3 scripts/sync_nav.py          # rewrite every page's nav block
    python3 scripts/sync_nav.py --check  # exit 1 if any copy differs (CI)

Everything between the sentinels is generated. Do not hand-edit it — edit here.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

CSS_START = "/* LS:NAV start — generated by scripts/sync_nav.py; do not hand-edit */"
CSS_END = "/* LS:NAV end */"
HTML_START = "<!-- LS:NAV start — generated by scripts/sync_nav.py; do not hand-edit -->"
HTML_END = "<!-- LS:NAV end -->"

# Deliberately uses LITERAL Night Ledger colours, not the pages' CSS variables.
# The sub-brands do not share the core palette's variable names — leaks.html even
# defines --ink as near-black for its paper-document look — so a bar built on
# var(--ink)/var(--surface) renders invisible there. Site chrome must look the same
# on every page, so it carries its own colours and inherits nothing.
CSS = CSS_START + """
.ls-nav{position:sticky;top:0;z-index:60;display:flex;align-items:center;gap:10px;
  padding:9px 14px;background:#0c1526;border-bottom:1px solid #1a2745;
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,system-ui,sans-serif;
  /* some pages turn <body> into a flex column at small widths and hand their own
     sections a negative `order` — without this the bar sorts BELOW the content it
     is supposed to sit above (chess put it a thousand pixels down the page) */
  order:-100;flex:0 0 auto}
.ls-nav a{border-bottom:0}                /* leaks underlines every link; not here */
.ls-brand{display:flex;align-items:center;gap:9px;text-decoration:none;color:#eef4ff;
  flex:0 0 auto;font-weight:600;font-size:15px;letter-spacing:-.01em}
.ls-brand svg{display:block}
.ls-word span{color:#9ec3ff}
/* the link row scrolls sideways instead of wrapping: a wallet's in-app browser is
   narrow, and a header that grows to three rows pushes the whole app off-screen */
.ls-links{display:flex;align-items:center;gap:4px;margin-left:auto;overflow-x:auto;
  scrollbar-width:none;-webkit-overflow-scrolling:touch}
.ls-links::-webkit-scrollbar{display:none}
.ls-links a{flex:0 0 auto;display:inline-flex;align-items:center;min-height:34px;
  padding:0 11px;border-radius:999px;text-decoration:none;white-space:nowrap;
  color:#8ba3cf;font-size:13.5px;font-weight:500;border:1px solid transparent;
  letter-spacing:0;text-transform:none}
.ls-links a:hover{color:#eef4ff;background:rgba(158,195,255,.10)}
.ls-links a:focus-visible{outline:2px solid #2f6bff;outline-offset:2px}
/* active page: driven by the data-page attribute on the body element — no JS */
body[data-page="index"]      .ls-links a[data-nav="index"],
body[data-page="calculator"] .ls-links a[data-nav="calculator"],
body[data-page="book"]       .ls-links a[data-nav="book"],
body[data-page="chess"]      .ls-links a[data-nav="chess"],
body[data-page="media"]      .ls-links a[data-nav="media"]{
  color:#eef4ff;border-color:#263760;background:rgba(158,195,255,.12)}
@media(max-width:430px){
  .ls-brand .ls-word{display:none}       /* mark only — buy the links their room back */
  .ls-links a{padding:0 9px;font-size:13px}
}
/* The constellation backdrop is a fixed 720px image, so it does not shrink with
   the viewport: on a phone it lands squarely on the headline instead of sitting
   off in the corner. Pull it back where the text needs the room. */
@media(max-width:760px){ .bg-grid{opacity:.42} }
""" + CSS_END

MARK = ('<svg viewBox="-60 -60 120 120" width="21" height="21" aria-hidden="true">'
        '<g fill="#aecbff"><circle cx="38" cy="0" r="9"/><circle cx="19" cy="32.9" r="9"/>'
        '<circle cx="-19" cy="32.9" r="9"/><circle cx="-19" cy="-32.9" r="9"/>'
        '<circle cx="19" cy="-32.9" r="9"/></g><circle cx="-38" cy="0" r="9" fill="#f6b45a"/>'
        '<circle r="16" fill="#2f6bff" stroke="#cfe0ff" stroke-width="2"/></svg>')

HTML = HTML_START + f"""
<header class="ls-nav">
  <a class="ls-brand" href="./index.html" aria-label="Ledger Scrolls — home">
    {MARK}<span class="ls-word">Ledger <span>Scrolls</span></span>
  </a>
  <nav class="ls-links" aria-label="Ledger Scrolls">
    <a href="./index.html" data-nav="index">Library</a>
    <a href="./calculator.html" data-nav="calculator">Mint a scroll</a>
    <a href="./ledger-book.html" data-nav="book">Ledger Book</a>
    <a href="./ledger-chess.html" data-nav="chess">Chess</a>
    <a href="./media.html" data-nav="media">What lives forever</a>
  </nav>
</header>
""" + HTML_END

# page -> data-page value (drives the active pill)
PAGES = {
    "index.html": "index",
    "calculator.html": "calculator",
    "ledger-book.html": "book",
    "ledger-chess.html": "chess",
    "media.html": "media",
    "leaks.html": "",        # sub-brand: gets the bar, claims no active pill
    "vault-tool.html": "",
}


def block(src, start, end):
    i, j = src.find(start), src.find(end)
    return (i, j + len(end)) if i != -1 and j != -1 else None


def apply(path, page_id, check):
    p = ROOT / path
    src = orig = p.read_text(encoding="utf-8")

    # --- CSS: replace between sentinels, else insert before </style> ---
    span = block(src, CSS_START, CSS_END)
    if span:
        src = src[:span[0]] + CSS + src[span[1]:]
    else:
        k = src.find("</style>")
        if k == -1:
            print(f"FAIL {path}: no </style>", file=sys.stderr); sys.exit(1)
        src = src[:k] + CSS + "\n" + src[k:]

    # Everything below must only ever look at the document BODY. The stylesheet can
    # legally contain the text "<body ...>" inside a comment or selector, and a naive
    # search finds that first — which silently injects the header into the <style>.
    head_end = src.find("</head>")
    if head_end == -1:
        print(f"FAIL {path}: no </head>", file=sys.stderr); sys.exit(1)

    # --- HTML: replace between sentinels, else insert right after <body...> ---
    span = block(src, HTML_START, HTML_END)
    if span:
        src = src[:span[0]] + HTML + src[span[1]:]
    else:
        m = re.compile(r"<body[^>]*>", re.I).search(src, head_end)
        if not m:
            print(f"FAIL {path}: no <body> after </head>", file=sys.stderr); sys.exit(1)
        src = src[:m.end()] + "\n" + HTML + src[m.end():]

    # --- the body's data-page attribute drives the active pill ---
    head_end = src.find("</head>")
    m = re.compile(r"<body[^>]*>", re.I).search(src, head_end)
    if not m:
        print(f"FAIL {path}: no <body> after </head>", file=sys.stderr); sys.exit(1)
    tag = re.sub(r'\s*data-page="[^"]*"', "", m.group(0))
    if page_id:
        tag = tag[:-1].rstrip() + f' data-page="{page_id}">'
    src = src[:m.start()] + tag + src[m.end():]

    if src == orig:
        return False
    if check:
        print(f"DRIFT {path}: nav block is not in sync with scripts/sync_nav.py")
        return True
    p.write_text(src, encoding="utf-8")
    print(f"ok   {path}")
    return True


check = "--check" in sys.argv
drift = [apply(f, pid, check) for f, pid in PAGES.items()]
if check:
    if any(drift):
        print("\nnav out of sync — run: python3 scripts/sync_nav.py")
        sys.exit(1)
    print(f"nav in sync across {len(PAGES)} pages")
elif not any(drift):
    print("nav already in sync")
