#!/usr/bin/env python3
"""Single source of truth for the shared site chrome — the top nav AND the footer.

The pages are self-contained on purpose (they get etched on-chain, and a reader
must work from a USB stick), so there is no runtime include to share. What we can
do is generate the shared blocks and let CI prove no copy has drifted:

    python3 scripts/sync_nav.py          # rewrite every page's nav + footer
    python3 scripts/sync_nav.py --check  # exit 1 if any copy differs (CI)

Everything between the sentinels is generated. Do not hand-edit it — edit here.

The top nav carries the five primary destinations. The footer links EVERY page to
every other, so nothing is an island — including the sub-brands (Leaks, Vault) and
the flagship delegation dApp (the Neon Door), which the compact nav leaves out.

Links use a per-page prefix ({P}) so pages in a subdirectory (build-a-reader/)
resolve to the same targets as the root pages.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

CSS_START = "/* LS:NAV start — generated by scripts/sync_nav.py; do not hand-edit */"
CSS_END = "/* LS:NAV end */"
NAV_START = "<!-- LS:NAV start — generated by scripts/sync_nav.py; do not hand-edit -->"
NAV_END = "<!-- LS:NAV end -->"
FOOT_START = "<!-- LS:FOOT start — generated by scripts/sync_nav.py; do not hand-edit -->"
FOOT_END = "<!-- LS:FOOT end -->"

# Deliberately uses LITERAL Night Ledger colours, not the pages' CSS variables.
# The sub-brands do not share the core palette's variable names — leaks.html even
# defines --ink as near-black for its paper-document look — so chrome built on
# var(--ink)/var(--surface) renders invisible there. Site chrome must look the same
# on every page, so it carries its own colours and inherits nothing.
CSS = CSS_START + """
.ls-nav{position:sticky;top:0;z-index:60;display:flex;align-items:center;gap:10px;
  padding:9px 14px;background:#0c1526;border-bottom:1px solid #1a2745;
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,system-ui,sans-serif;
  /* some pages turn <body> into a flex column at small widths and hand their own
     sections a negative `order` — without this the bar sorts BELOW the content it
     is supposed to sit above (chess put it a thousand pixels down the page) */
  order:-100;flex:0 0 auto}
.ls-nav a{border-bottom:0}                /* leaks underlines every link; not here */
.ls-brand{display:flex;align-items:center;gap:9px;text-decoration:none;color:#eef4ff;
  flex:0 0 auto;font-weight:600;font-size:15px;letter-spacing:-.01em}
.ls-brand svg{display:block}
.ls-word span{color:#9ec3ff}
/* the link row scrolls sideways instead of wrapping: a wallet's in-app browser is
   narrow, and a header that grows to three rows pushes the whole app off-screen */
.ls-links{display:flex;align-items:center;gap:4px;margin-left:auto;overflow-x:auto;
  scrollbar-width:none;-webkit-overflow-scrolling:touch}
.ls-links::-webkit-scrollbar{display:none}
.ls-links a{flex:0 0 auto;display:inline-flex;align-items:center;min-height:34px;
  padding:0 11px;border-radius:999px;text-decoration:none;white-space:nowrap;
  color:#8ba3cf;font-size:13.5px;font-weight:500;border:1px solid transparent;
  letter-spacing:0;text-transform:none}
.ls-links a:hover{color:#eef4ff;background:rgba(158,195,255,.10)}
.ls-links a:focus-visible{outline:2px solid #2f6bff;outline-offset:2px}
/* active page: driven by the data-page attribute on the body element — no JS */
body[data-page="index"]      .ls-links a[data-nav="index"],
body[data-page="calculator"] .ls-links a[data-nav="calculator"],
body[data-page="book"]       .ls-links a[data-nav="book"],
body[data-page="chess"]      .ls-links a[data-nav="chess"],
body[data-page="media"]      .ls-links a[data-nav="media"]{
  color:#eef4ff;border-color:#263760;background:rgba(158,195,255,.12)}
@media(max-width:430px){
  .ls-brand .ls-word{display:none}       /* mark only — buy the links their room back */
  .ls-links a{padding:0 9px;font-size:13px}
}
/* The constellation backdrop is a fixed 720px image, so it does not shrink with
   the viewport: on a phone it lands squarely on the headline instead of sitting
   off in the corner. Pull it back where the text needs the room. */
@media(max-width:760px){ .bg-grid{opacity:.42} }

/* ---- shared footer: every page reaches every other page from here ---- */
.ls-foot{order:100;margin-top:auto;background:#0a1122;border-top:1px solid #1a2745;
  color:#8ba3cf;
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,system-ui,sans-serif}
.ls-foot a{color:#8ba3cf;text-decoration:none;border-bottom:0}
.ls-foot a:hover{color:#eef4ff}
.ls-foot a:focus-visible{outline:2px solid #2f6bff;outline-offset:2px;border-radius:4px}
.ls-foot-inner{max-width:1080px;margin:0 auto;padding:40px 20px 12px;
  display:flex;flex-wrap:wrap;gap:34px}
.ls-foot-brand{flex:1 1 250px;min-width:230px}
.ls-foot-mark{display:inline-flex;align-items:center;gap:9px;color:#eef4ff;
  font-weight:600;font-size:16px;letter-spacing:-.01em}
.ls-foot-mark b{color:#9ec3ff;font-weight:600}
.ls-foot-tag{margin-top:11px;font-size:13.5px;line-height:1.6;max-width:40ch;color:#8ba3cf}
.ls-foot-cols{display:flex;flex-wrap:wrap;gap:26px 42px;flex:2 1 470px}
.ls-foot-col{display:flex;flex-direction:column;gap:9px;min-width:118px}
.ls-foot-col h4{color:#67789c;font-size:11.5px;letter-spacing:.15em;text-transform:uppercase;
  margin:0 0 3px;font-weight:600}
.ls-foot-col a{font-size:14px;line-height:1.3}
.ls-foot-legal{max-width:1080px;margin:6px auto 0;padding:15px 20px 30px;
  border-top:1px solid #131f3f;font-size:12px;color:#5c6b8a}
@media(max-width:560px){
  .ls-foot-inner{gap:26px;padding-top:32px}
  .ls-foot-cols{gap:22px 30px}
}
""" + CSS_END

MARK = ('<svg viewBox="-60 -60 120 120" width="21" height="21" aria-hidden="true">'
        '<g fill="#aecbff"><circle cx="38" cy="0" r="9"/><circle cx="19" cy="32.9" r="9"/>'
        '<circle cx="-19" cy="32.9" r="9"/><circle cx="-19" cy="-32.9" r="9"/>'
        '<circle cx="19" cy="-32.9" r="9"/></g><circle cx="-38" cy="0" r="9" fill="#f6b45a"/>'
        '<circle r="16" fill="#2f6bff" stroke="#cfe0ff" stroke-width="2"/></svg>')

FOOT_MARK = ('<svg viewBox="-60 -60 120 120" width="20" height="20" aria-hidden="true">'
             '<g fill="#aecbff"><circle cx="38" cy="0" r="9"/><circle cx="19" cy="32.9" r="9"/>'
             '<circle cx="-19" cy="32.9" r="9"/><circle cx="-19" cy="-32.9" r="9"/>'
             '<circle cx="19" cy="-32.9" r="9"/></g><circle cx="-38" cy="0" r="9" fill="#f6b45a"/>'
             '<circle r="16" fill="#2f6bff" stroke="#cfe0ff" stroke-width="2"/></svg>')


def nav_html(P):
    return NAV_START + f"""
<header class="ls-nav">
  <a class="ls-brand" href="{P}index.html" aria-label="Ledger Scrolls — home">
    {MARK}<span class="ls-word">Ledger <span>Scrolls</span></span>
  </a>
  <nav class="ls-links" aria-label="Ledger Scrolls">
    <a href="{P}index.html" data-nav="index">Library</a>
    <a href="{P}calculator.html" data-nav="calculator">Mint a scroll</a>
    <a href="{P}ledger-book.html" data-nav="book">Ledger Book</a>
    <a href="{P}ledger-chess.html" data-nav="chess">Chess</a>
    <a href="{P}media.html" data-nav="media">What lives forever</a>
  </nav>
</header>
""" + NAV_END


def foot_html(P):
    return FOOT_START + f"""
<footer class="ls-foot">
  <div class="ls-foot-inner">
    <div class="ls-foot-brand">
      <a class="ls-foot-mark" href="{P}index.html" aria-label="Ledger Scrolls — home">
        {FOOT_MARK}<span>Ledger <b>Scrolls</b></span>
      </a>
      <p class="ls-foot-tag">A library that cannot burn. Immutable media written into
      Cardano itself — no accounts, no servers of record, verified on every read.</p>
    </div>
    <nav class="ls-foot-cols" aria-label="All Ledger Scrolls pages">
      <div class="ls-foot-col">
        <h4>Read</h4>
        <a href="{P}index.html">The Library</a>
        <a href="{P}build-a-reader/">Build a reader</a>
      </div>
      <div class="ls-foot-col">
        <h4>Create</h4>
        <a href="{P}calculator.html">Mint a scroll</a>
        <a href="{P}ledger-book.html">Ledger Book</a>
        <a href="{P}vault-tool.html">Vault Tool</a>
      </div>
      <div class="ls-foot-col">
        <h4>Explore</h4>
        <a href="{P}ledger-chess.html">Ledger Chess</a>
        <a href="{P}media.html">What lives forever</a>
        <a href="{P}leaks.html">BEACN Leaks</a>
        <a href="{P}neon-door.html">The Neon Door</a>
      </div>
      <div class="ls-foot-col">
        <h4>Project</h4>
        <a href="https://github.com/BEACNpool/ledger-scrolls">Source &amp; specs</a>
        <a href="{P}media.html">How it works</a>
      </div>
    </nav>
  </div>
  <div class="ls-foot-legal">Open protocol &middot; MIT &middot; maintained by BEACN, verified by you.</div>
</footer>
""" + FOOT_END


# page -> (data-page value | "", href prefix to repo root)
PAGES = {
    "index.html": ("index", "./"),
    "calculator.html": ("calculator", "./"),
    "ledger-book.html": ("book", "./"),
    "ledger-chess.html": ("chess", "./"),
    "media.html": ("media", "./"),
    "leaks.html": ("", "./"),            # sub-brand: gets the chrome, claims no active pill
    "vault-tool.html": ("", "./"),
    "build-a-reader/index.html": ("", "../"),
}


def block(src, start, end):
    i, j = src.find(start), src.find(end)
    return (i, j + len(end)) if i != -1 and j != -1 else None


def apply(path, page_id, prefix, check):
    p = ROOT / path
    src = orig = p.read_text(encoding="utf-8")

    # --- CSS: replace between sentinels, else insert before the LAST </style> in
    #     <head> (pages can carry a literal </style> inside a JS string later on) ---
    span = block(src, CSS_START, CSS_END)
    if span:
        src = src[:span[0]] + CSS + src[span[1]:]
    else:
        head_end = src.find("</head>")
        if head_end == -1:
            print(f"FAIL {path}: no </head>", file=sys.stderr); sys.exit(1)
        k = src.rfind("</style>", 0, head_end)
        if k == -1:
            print(f"FAIL {path}: no </style> in <head>", file=sys.stderr); sys.exit(1)
        src = src[:k] + CSS + "\n" + src[k:]

    # Everything below must only look at the document BODY. The stylesheet can
    # legally contain "<body ...>" in a comment or selector; a naive search finds
    # that first and injects the chrome into the <style>.
    head_end = src.find("</head>")

    # --- NAV: replace between sentinels, else insert right after <body...> ---
    span = block(src, NAV_START, NAV_END)
    nav = nav_html(prefix)
    if span:
        src = src[:span[0]] + nav + src[span[1]:]
    else:
        m = re.compile(r"<body[^>]*>", re.I).search(src, head_end)
        if not m:
            print(f"FAIL {path}: no <body> after </head>", file=sys.stderr); sys.exit(1)
        src = src[:m.end()] + "\n" + nav + src[m.end():]

    # --- FOOTER: replace between sentinels, else insert right before </body> ---
    span = block(src, FOOT_START, FOOT_END)
    foot = foot_html(prefix)
    if span:
        src = src[:span[0]] + foot + src[span[1]:]
    else:
        k = src.rfind("</body>")
        if k == -1:
            print(f"FAIL {path}: no </body>", file=sys.stderr); sys.exit(1)
        src = src[:k] + foot + "\n" + src[k:]

    # --- the body's data-page attribute drives the active pill ---
    head_end = src.find("</head>")
    m = re.compile(r"<body[^>]*>", re.I).search(src, head_end)
    if not m:
        print(f"FAIL {path}: no <body> after </head>", file=sys.stderr); sys.exit(1)
    tag = re.sub(r'\s*data-page="[^"]*"', "", m.group(0))
    if page_id:
        tag = tag[:-1].rstrip() + f' data-page="{page_id}">'
    src = src[:m.start()] + tag + src[m.end():]

    if src == orig:
        return False
    if check:
        print(f"DRIFT {path}: chrome is not in sync with scripts/sync_nav.py")
        return True
    p.write_text(src, encoding="utf-8")
    print(f"ok   {path}")
    return True


check = "--check" in sys.argv
drift = [apply(f, pid, prefix, check) for f, (pid, prefix) in PAGES.items()]
if check:
    if any(drift):
        print("\nchrome out of sync — run: python3 scripts/sync_nav.py")
        sys.exit(1)
    print(f"nav + footer in sync across {len(PAGES)} pages")
elif not any(drift):
    print("chrome already in sync")
